# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=37

# Estabilización del Daemon de Kotlin
kotlin.daemon.jvm.options=-Xmx2048m
kotlin.incremental=false
